version: "3.8"
services:
  # Filebeat to read logs and ship them to Redis.
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.3
    command: filebeat -e --strict.perms=false
    volumes:
      - ./data/filebeat:/usr/share/filebeat/data
      - ./init/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../app/logs:/var/log/app:ro
    restart: always

  # Redis as buffer.
  redis:
    image: redis:6.0.9
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    restart: always

  # ELK for visualizing logs.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    command: logstash
    volumes:
      - ./data/logstash:/usr/share/logstash/data
      - ./init/logstash/config:/usr/share/logstash/config:ro
      - ./init/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./init/logstash/scripts:/usr/share/logstash/scripts:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - 5601:5601
    restart: always